blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from post.views import post_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls', namespace='post')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('accounts/', include('allauth.urls')),
    path('', post_list, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('post-list/', views.post_list, name="post_list"),
    path('post-list/<int:id>/', views.post_detail, name='post_detail'),
    path('post-create/', views.post_create, name='post_create'),
    path('post-delete/<int:id>/', views.post_delete, name='post_delete'),
    path('post-update/<int:id>/', views.post_update, name='post_update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name='userprofile'

urlpatterns=[
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>

    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en-GB">

<head>

    <meta charset="utf-8">
    <!-- Title -->
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<link rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" 
      crossorigin="anonymous">
      
<body>

    <!-- Header -->
    {% include 'header.html' %}
    <div id="wrapper">
        {% block content %}
        {% endblock content %}
        <div id="push"
        </div>
    </div>

    <!-- Footer -->
    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery-3.4.1.js' %}"></script> 
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    {% block script %}{% endblock script %}
    {% include 'back_to_top_func.html' %}
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>
</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white"> WAD2 Blog </p>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <a class="navbar-brand" href="#">WAD2 Blog</a>

    <div>
      <ul class="navbar-nav">
        <li class="nav-item">
        
        <!-- back to Home page when 'Posts' buttom is clicked-->
          <a class="nav-link" href="{% url 'post:post_list' %}">Posts| </a>
        </li>

        {% if user.is_authenticated %}
        <!-- dropdown menu if user logined-->
            <li class="nav-item dropdown">
              <a class=:"nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'> Information </a>
                <a class="dropdown-item" href='{% url "post:post_create" %}'> Publish a post </a> 
                <a class="dropdown-item" href='{% url "userprofile:logout" %}'> Logout </a>
                <a class="dropdown-item" href="#" onclick="user_delete()"> Delete account</a>
              </div>
            </li>

            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userprofile:login' %}"> Login </a>
              </li>

        {% endif %}
        
      </ul>
    </div>
  </div>
</nav>

{% if user.is_authenticated %}
<form 
    style="display:none;" 
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}" 
    method="POST"
>
{% csrf_token %}
    <button type="submit"> Submit </button>
  </form>
      <script>
          function user_delete() {
              // layer pop-up windows
              layer.open({
                  title: "Delete Confirmation",
                  content: "Confirm to delete?",
                  yes: function(index, layero) {
                      $('form#user_delete button').click();
                      layer.close(index);
                  },
              })
          }
        </script>
{% endif %}