blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from post.views import post_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls', namespace='post')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('accounts/', include('allauth.urls')),
    path('', post_list, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # comment
    path('post-comment/<int:post_id>/', views.post_comment, name='post_comment'),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('post-list/', views.post_list, name="post_list"),
    path('post-list/<int:id>/', views.post_detail, name='post_detail'),
    path('post-create/', views.post_create, name='post_create'),
    path('post-delete/<int:id>/', views.post_delete, name='post_delete'),
    path('post-update/<int:id>/', views.post_update, name='post_update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name='userprofile'

urlpatterns=[
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from taggit.managers import TaggableManager

# Create your models here.

class PostColumn(models.Model):

    title = models.CharField(max_length=100, blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    column = models.ForeignKey(
        PostColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='post'
    )
    tags = TaggableManager(blank=True)
    title = models.CharField(max_length = 50)
    body = models.TextField()

    avatar = models.ImageField(upload_to='post/%Y%m%d/', blank=True)
    def save(self, *args, **kwargs):
        # save avatar
        post = super(Post, self).save(*args, **kwargs)
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return post
        
    # auto time set
    created_time = models.DateTimeField(default = timezone.now)
    update_time = models.DateTimeField(auto_now=True)

    total_views = models.PositiveIntegerField(default=0)


    ## latest posts on top
    class Meta:
        ordering = ('-created_time', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:post_detail', args=[self.id])

post/forms.py
from django import forms
from .models import Post

# allow users publish posts using forms
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('title', 'body', 'tags', 'avatar')

post/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import PostForm
from .models import Post
from .models import PostColumn
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm
import markdown
# Create your views here.

def post_list(request):

    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    post_list = Post.objects.all()

    if search:
        post_list = post_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

    if tag and tag != 'None':
        post_list = post_list.filter(tags__name__in=[tag])

    if order == 'total_views':
        post_list = post_list.order_by('-total_views')

    if column is not None and column.isdigit():
        post_list = post_list.filter(column=column)

    paginator = Paginator(post_list, 3)
    page = request.GET.get('page')
    posts = paginator.get_page(page)


    context = {
        'posts': posts,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
    }
    
    return render(request, 'post/list.html', context)
def post_detail(request, id):
    ## id = Primary Key
    post = Post.objects.get(id=id)
    comments = Comment.objects.filter(post=id)
    comment_form = CommentForm()
    post.total_views += 1
    post.save(update_fields=['total_views'])

    ## translate markdown to html 
    md = markdown.Markdown(
        extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.toc',
        'markdown.extensions.codehilite',
    ])
    post.body = md.convert(post.body)
    context = { 'post': post, 'toc': md.toc, 'comments': comments, 'comment_form': comment_form,}
    return render(request, 'post/detail.html', context)

@login_required(login_url='/userprofile/login/')
def post_create(request):
    # determine whether the user want to publish a post
    if request.method == "POST":
        post_form = PostForm(request.POST, request.FILES)

        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.author = User.objects.get(id=request.user.id)
            new_post.save()
            # many to many relationship
            post_form.save_m2m()
            return redirect("post:post_list")
        else:
            return HttpResponse("Invalid content, please edit again")

    # if the user not going to publish a post
    else:
        post_form=PostForm()
        context = {'post_post': post_form}

        return render(request, 'post/create.html', context)

def post_delete(request, id):
    # delete post by its id
    # then back to the post list
    post = Post.objects.get(id=id)
    post.delete()
    return redirect("post:post_list")

    # update a post
@login_required(login_url='/userprofile/login/')
def post_update(request, id):
        # using POST 
        # enter oroginal form by GET 
        # redirect to the modified psot 

    post=Post.objects.get(id=id)
    if request.user != post.author:
        return HttpResponse("You can't edit this post") 

    if request.method == "POST":
        post_form = PostForm(data=request.POST)

        if post_form.is_valid():
            # overwrite the original context
            post.title = request.POST['title']
            post.body = request.POST['body']

            if request.POST['column'] != 'none':
                post.column = PostColumn.objects.get(id=request.POST['column'])
            else:
                post.column = None

            post.save()
            return redirect("post:post_detail", id=id)
        else:
            columns = PostColumn.objects.all()
            context = { 
            'post': post, 
            'post_form': post_form,
            'columns': columns,
        }
            return HttpResponse("Invalid content, please edit again")
    else:
        post_form = PostForm()
        context = {'post': post, 'post_form': post_form}
        return render(request, 'post/update.html', context)

templates/post/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Publich a post
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>

                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <!-- Avatar  -->
                    <div class="form-group">
                        <label for="avatar"> Avatar: </label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>

                    <!-- Tages -->
                    <div class="form-group">
                        <label for="tags">Tags: </label>
                        <input type="text" 
                            class="form-control col-3" 
                            id="tags" 
                            name="tags"
                        >
                    </div>

                    <!-- title-->
                    <div class="form-group">
                        <label for="title"> Post title:</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>

                    <!-- category -->
                    <div class="form-group">
                        <label for="column">Category:</label>
                        <select class="form-control" 
                                id="column" 
                                name="column"
                        >
                                <option value="none">-</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}">{{ column }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <!-- content -->
                    <div class="form-group">
                        <label for="body"> Content: </label>
                        <textarea type = "text" class="form-control" id="body" name="body" rows="12"> </textarea>
                    </div>

                    <button type="submit" class="btn btn-primary"> Finished </button>
                </form>
                
            </div>
        </div>
    </div>

{% endblock content %}

templates/post/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Post detail
{% endblock title %}

{% block content %}

<!-- post detail -->
<div class="container">
    <div class="row">

    <!-- title && author -->
    <h1 class="col-12 mt-4 mb-4"> {{post.title}}  </h1>
        <div class="col-12 alert alert-success">
            <div>
                Author: {{ post.author }}
                {% if user == post.author %}
                    <a href="#" onclick="confirm_delete()"> Delete post </a>
                    <a href="{% url "post:post_update" post.id %}"> | Edit post </a>
                {% endif %}
            </div>
            <div>
                views: {{ post.total_views }}
            </div>
        </div>

        <!-- category -->
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <h4><strong>Category:</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>

        <style>
        .sidebar{
            will-change: min-height;
        }

        .sidebar__inner{
            transform: translate(0, 0);
            transform: translate3d(0, 0, 0);
            will-change: position, transform;
        }
</style>
    <!-- post content -->
        <div class="col-12">
            <p>{{post.body|safe}}</p>
        </div>
<hr>
    {% if user.is_authenticated %}
        <div>
            <form 
                action="{% url 'comment:post_comment' post.id %}" 
                method="POST"
            >
            {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            Comments:
                        </strong>
                    </label>

                    <div>
                        {{ comment_form.media }}
                        {{ comment_form.body }}
                    </div>
        
                </div>
                <!-- submit button-->
                <button type="submit" class="btn btn-primary "> send </button> <br>                   
            </form>
        </div>

    {% else %}
        <br>
        <h5 class="row justify-content-center">
            Comment after <a href="{% url 'userprofile:login' %}"> login </a>
        </h5>
        <br>
    {% endif %}

    <!-- show comments -->
    <div>
        {% for comment in comments %}
            <hr>
            <p>
                <strong style="color: pink">
                    {{ comment.user }}
                </strong> at:
                <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> says:
            </p>
            <pre style="font-family: inherit; font-size: 1em;">
                {{ comment.body|safe }}</pre>
        {% endfor %}
    </div>
</div>
    </div>
</div>

<!-- delete post -->
<script>
    function confirm_delete() {
        // use the layer plugin 
        // to confirm the Delete post buttom would not be misclicked
        layer.open({
            title: "Post Deletion",
            content: "Confirm to delete?",
            // goto delete if yes is clicked
            yes: function(index, layero){
                location.href='{% url "post:post_delete" post.id %}'
            },
        })
    }
</script> 

{% endblock content %}

{% block script %}
<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>
{% endblock script %}

templates/post/list.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- Home -->
{% block title %}
    Home
{% endblock title %}

{% block content %}

<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            <a href="{% url 'post:post_list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">
                Latest
            </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'post:post_list' %}?order=total_views&search={{ search }}&column={{ column }}&tag={{ tag }}">
                    Hotest
                </a>
            </li>
        </ol>
    </nav>

    <!-- search bar -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text" 
                    class="form-control mb-2 mr-sm-2" 
                    name="search" 
                    placeholder="Searching..." 
                    required
                >
            </form>
        </div>
    </div>

    <!-- search hints -->
    {% if search %}
        {% if posts %}
            <h4><span style="color: red">"{{ search }}"</span>Search results"</h4>
            <hr>        
        {% else %}
            <h4>No<span style="color: red">"{{ search }}"</span>posts.</h4>
            <hr>
        {% endif %}
    {% endif %}
    
    <div class="row mt-2">
        {% for post in posts %}
                <!-- Avatar -->
            {% if post.avatar %}
                <div class="col-3">
                    <img src="{{ post.avatar.url }}" 
                        alt="avatar" 
                        style="max-width:100%; border-radius: 20px"
                    >
                </div>
            {% endif %}

            <!-- post content -->
            <div class="col">
                {% if post.column %}
                    <button type="button" 
                        class="btn btn-sm mb-2
                            {% if postx.column.title == 'cooking' %}
                                btn-success
                            {% elif post.column.title == 'Python' %}
                                btn-danger
                            {% elif post.column.title == 'books' %}
                                btn-warning
                            {% endif %}
                        "
                    >
                        {{ post.column }}
                    </button>
                {% endif %}
                
                <!-- Tags -->
                <span>
                    {% for tag in post.tags.all %}
                        <a href="{% url 'post:post_list' %}?tag={{ tag }}"
                        class="badge badge-secondary" 
                        >
                            {{ tag }}
                        </a>
                    {% endfor %}
                </span>

                <!-- Title -->
                <h4>
                    <b>
                        <a href="{% url 'post:post_detail' post.id %}"
                        style="color: black;" 
                        >
                            {{ post.title }}
                        </a>
                    </b>
                </h4>
                
                <!-- Summary -->
                <div class="card-body">
                    <p class="card-text">{{ post.body|slice:'50' }}...</p>
                </div>

                <!-- Footer -->
                <p>

                <span>
                    <i class="fas fa-eye" style="color: lightskyblue;"></i>
                    {{ post.total_views }}&nbsp;&nbsp;&nbsp;
                </span>
                <span>
                    <i class="fas fa-comments" style="color: yellowgreen;"></i>
                    {{ post.comments.count }}&nbsp;&nbsp;&nbsp;
                </span>
                <span>
                    <i class="fas fa-clock" style="color: pink;"></i>
                    {{ post.created|date:'Y-m-d' }}
                </span>
            </p>
            <hr>
        </div>
        <hr style="width: 100%;"/>
    {% endfor %}
</div>


    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- previous page if not first page -->
                {% if posts.has_previous %}
                    <a href="?page=1 &order={{ order }} &search={{ search }}" class="btn btn-success">
                    <span>...</span>

                    <a href="?page={{ posts.previous_page_number }}&order={{ order }}&search={{ search }}" 
                    class="btn btn-secondary">
                    </a>
                {% endif %}

                <!-- current page -->
                <span class="current btn btn-danger btn-lg">
                    {{ posts.number }}
                </span>

                <!-- next page if not last page -->
                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}&order={{ order }}&search={{ search }}" 
                    class="btn btn-secondary">
                    </a>
                    <span>...</span>

                    <a href="?page={{ posts.paginator.num_pages }}&order={{ order }}&search={{ search }}"
                    class="btn btn-success">
                    </a>
                {% endif %}
            </span>
        </div>
    </div>

</div>
{% endblock content %}

templates/post/update.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Updata post
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>

                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="title"> Post title </label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ post.title }}">
                    </div>

                    <!-- category -->
                    <div class="form-group">
                        <label for="column">cagetory</label>
                        <select class="form-control" 
                                id="column" 
                                name="column"
                        >
                                <option value="none">Select</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}"
                                    {% if column.id == post.column.id %}
                                        selected
                                    {% endif %}
                                >
                                    {{ column }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="body"> Post Content </label>
                        <textarea type="text" class="form-control" id="body" name="body" rows="12">{{pody.body}} </textarea>
                    </div>

                    <button type="submit" class="btn btn-primary"> Finished </button>
                </form>

            </div>
        </div>
    </div>

{% endblock content%}